/-
HELIOS V5 E1 — Density Theorem (12-plane bundle).

HELIOS-E1 guard

Per `docs/HELIOS_V5_DOC_6_THEOREM_CANON.md` §1 E1 +
`EPISTEMOS_FINAL_SEVEN_THEOREMS_v2_HARDENED.md` PART I T1
(v2.0 hardened, P-scoped):

  Let X = A_1 × A_2 × A_3 × A_4 × A_5 × A_6 ⊂ ℂ⁶ be the compact
  branch-safe 12-plane bundle, where each A_k ⊂ ℂ is a closed
  annular sector avoiding arg = ±π by margin ε > 0 (ε = π/16)
  and r_min ≤ |z| ≤ r_max with r_min = 2^(-12), r_max = 2^12.
  (v2.1 patch: PRODUCT, not disjoint union.)

  Let A_Morph(X) = alg⟨1, x_1, …, x_12, eml, conjugation⟩ ⊂
  C(X, ℂ) be the unital algebra generated by:
    * the constant 1
    * the 12 real coordinate observables x_1, …, x_12 (real +
      imag parts of the six complex coordinates)
    * eml (the EML point-evaluation operator)
    * conjugation (complex conjugation)

  Then A_Morph(X) is uniformly dense in C(X, ℂ).

**Status (v2.0):** P (Peer-reviewed/Stone-Weierstrass) ONLY with
coordinate observables + conjugation present. EML-alone density
remains C (open conjecture per F7e falsifier).

mathlib4 anchor: `Mathlib.Topology.Algebra.StoneWeierstrass`.

Sorry budget at lock: ≤ 2.
-/

import Mathlib.Topology.Algebra.StoneWeierstrass

namespace Epistemos.E1

/-- One annular sector A_k ⊂ ℂ in the 12-plane bundle. Closed,
branch-safe (avoiding arg = ±π by margin ε), bounded by
r_min ≤ |z| ≤ r_max. -/
structure AnnularSector where
  r_min : Float       -- 2^(-12) per v2.0 hardened
  r_max : Float       -- 2^12
  arg_margin : Float  -- ε = π/16

/-- Default annular-sector parameters per v2.0 §T1. -/
def AnnularSector.default : AnnularSector :=
  { r_min := 1.0 / 4096.0    -- 2^(-12)
    r_max := 4096.0           -- 2^12
    arg_margin := 0.1963495408 -- π/16 ≈ 0.196
  }

/-- The 12-plane bundle X = A_1 × A_2 × A_3 × A_4 × A_5 × A_6 ⊂ ℂ⁶
(v2.1 patch: PRODUCT, not disjoint union per v1). -/
def Chart6 : Type := ℂ × ℂ × ℂ × ℂ × ℂ × ℂ

/-- The unital algebra A_Morph(X) generated by `{1, x_1..x_12,
eml, conjugation}`. Density of this algebra in `C(X, ℂ)` is
**P-grade** when ALL generators are present; **C** if eml alone
is the only nontrivial generator (open per F7e falsifier). -/
inductive AMorphGenerator
  | constant_one
  | coord_real (k : Fin 6)    -- real part of coordinate k
  | coord_imag (k : Fin 6)    -- imag part of coordinate k
  | eml_eval                  -- EML point-evaluation
  | conjugation               -- complex conjugation

/-- The full generator list per the v2.0 hardened statement.
Stone-Weierstrass density requires the full set; subsets do NOT
suffice (see EML-alone-density open conjecture). -/
def fullGeneratorList : List AMorphGenerator :=
  [.constant_one,
   .coord_real 0, .coord_imag 0,
   .coord_real 1, .coord_imag 1,
   .coord_real 2, .coord_imag 2,
   .coord_real 3, .coord_imag 3,
   .coord_real 4, .coord_imag 4,
   .coord_real 5, .coord_imag 5,
   .eml_eval,
   .conjugation]

/-- Density theorem (P-scoped). -/
theorem density_with_full_generators (X : Set Chart6) (hX : X.Nonempty) :
    -- Real Stone-Weierstrass elaboration lands per W24.b.
    -- The generator list above must be complete; restricting
    -- to {.constant_one, .eml_eval} yields the C conjecture.
    True := by
  sorry

end Epistemos.E1
